### ISSUE TITLE
Suggestion: Rename to `auto-cancel-redundant-workflow`

### ISSUE THREAD

**Issue by bendavies** [technote-space/auto-cancel-redundant-workflow#51]
## Please describe your suggestion: 提案の概要
Rename this action to `auto-cancel-redundant-workflow`, since it cancels workflows, not jobs.

Just a small thing i spotted, no big deal 👍 

Thanks for the great action!

**Comment by technote-space** [comment]
Thank you for your issue.
The repository name has been changed.
